/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 console.glb 
Author: DAVID.3D.ART (https://sketchfab.com/david3dart)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/data-center-rack-f178ec0a9c5f4605a5acbaaeb52dc721
Title: Data center rack
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConsoleModel(props) {
  const { nodes, materials } = useGLTF('/console.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Mat_2} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/console.glb')
